//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace JYGASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deudor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deudor()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name ="Nombre")]
        [RegularExpression("@[A-Za-z]+")]
        public string nombre { get; set; }
        [Required]
        [Display(Name = "Apellido paterno")]
        [RegularExpression("@[A-Za-z]+")]
        public string apell_pat { get; set; }
        [Required]
        [Display(Name = "Apellido Materno")]
        [RegularExpression("@[A-Za-z]+")]
        public string apell_mat { get; set; }
        [Required]
        [Display(Name = "Cantidad prestada")]
        [RegularExpression("@[0-9]+")]
        public decimal cant_p { get; set; }
        [Required]
        [Display(Name = "Teléfono")]
        [MaxLength(8,ErrorMessage ="El teléfono debe de tener como máximo 8 números")]
        [RegularExpression("@[0-9]{6,8}")]
        public string telef { get; set; }
        [Required]
        [Display(Name = "Correo")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Fecha de préstamo")]
        public System.DateTime fecha_p { get; set; }
        [Required]
        [Display(Name = "Día de cobro")]
        public int dia_c { get; set; }
        [Required]
        [Display(Name = "Meses de Préstamo")]
        public int meses_p { get; set; }
        [Required]
        [RegularExpression("@[1-9]+")]
        [Display(Name = "Intereses")]
        public int intereses { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
