//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace JYGASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Selecione el deudor")]
        public Nullable<int> id_deudor { get; set; }
        [Required]
        [Display(Name = "Cantidad")]
        [RegularExpression("@[0-9]+")]
        public Nullable<decimal> cantidad { get; set; }
        [Required]
        [Display(Name = "Fecha de entrega")]
        public System.DateTime fecha { get; set; }
        [Required]
        [Display(Name = "Interes")]
        public Nullable<bool> interes { get; set; }
    
        public virtual Deudor Deudor { get; set; }
    }
}
